name: iit_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  provider: ^6.0.5
  responsive_sizer: ^3.1.1
  typewritertext: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
