// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIoWpPLjqyfELHntzt50tFzv_1HUuMaM',
    appId: '1:996025416782:web:07ef31aa516d7f3a05171f',
    messagingSenderId: '996025416782',
    projectId: 'iit-chat',
    authDomain: 'iit-chat.firebaseapp.com',
    storageBucket: 'iit-chat.appspot.com',
    measurementId: 'G-MH24ZRXLMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmsSQ4Nn-eNuPkxn51WeA5UCytILyW6g',
    appId: '1:996025416782:android:cf8880acd4c54a5c05171f',
    messagingSenderId: '996025416782',
    projectId: 'iit-chat',
    storageBucket: 'iit-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVue_U6Qs4dq9Kwf_QOGqwqKYw_pfTMp8',
    appId: '1:996025416782:ios:a8e315966457510505171f',
    messagingSenderId: '996025416782',
    projectId: 'iit-chat',
    storageBucket: 'iit-chat.appspot.com',
    iosClientId: '996025416782-feke3uqf0oofdes6e3ak7ufgq4uvkpjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.iitChat',
  );
}
